name: fastvideoplayer
description: This is the official intuitive video player with cache support for FastAd.
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1
  flutter_hooks: ^0.20.0
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
